/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_MP3_FILES           3
#define MMAP_MP3_CHECKSUM        0xE57B

enum MMAP_MP3_LISTS {
    MMAP_MP3_FORELISE_MP3 = 0,        /*!< ForElise.mp3 */
    MMAP_MP3_LEMONTREE_MP3 = 1,        /*!< LemonTree.mp3 */
    MMAP_MP3_WAKAWAKA_MP3 = 2,        /*!< WakaWaka.mp3 */
};
