/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_MUSIC_FILES           1
#define MMAP_MUSIC_CHECKSUM        0x77AD

enum MMAP_MUSIC_LISTS {
    MMAP_MUSIC_MUSIC_PCM = 0,        /*!< music.pcm */
};
