/*
 * SPDX-FileCopyrightText: 2022-2026 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_GIFS_FILES           6
#define MMAP_GIFS_CHECKSUM        0x91C8

enum MMAP_GIFS_LISTS {
    MMAP_GIFS_ANGER_GIF = 0,        /*!< anger.gif */
    MMAP_GIFS_BUXUE_GIF = 1,        /*!< buxue.gif */
    MMAP_GIFS_HAPPY_GIF = 2,        /*!< happy.gif */
    MMAP_GIFS_SAD_GIF = 3,        /*!< sad.gif */
    MMAP_GIFS_SCARE_GIF = 4,        /*!< scare.gif */
    MMAP_GIFS_STATICSTATE_GIF = 5,        /*!< staticstate.gif */
};
